FilesBundle\Entity\Images:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        photo:
            type: string
            length: 255


    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
